Repository roaldnefs/python-transip, pull requests merged in 2021-02, with the labels that each got.

#45 Add colocation endpoints
  CHANGELOG.md
  README.md
  tests/services/test_colocations.py
  transip/__init__.py
  transip/v6/objects.py
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#47 fix: add argument to disable IP whitelisting (#47)
  CHANGELOG.md
  transip/__init__.py
  transip/utils.py
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#48 Bump version to 0.5.0
  CHANGELOG.md
  transip/__init__.py
Labels: Priority: Medium, Status: Accepted, Type: Maintenance
